Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
namespace SportsStore.Components
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            this.cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
namespace SportsStore.Components
{
    public class NavigationMenuViewComponent:ViewComponent
    {
        public IStoreRepository repository;
        public NavigationMenuViewComponent(IStoreRepository repository)
        {
            this.repository = repository;
        }
        public IViewComponentResult Invoke()
        {
            ViewData["cat"] = RouteData?.Values["category"];
            return View(repository.Products.Select(p => p.Category)
                .Distinct()
                .OrderBy(x => x));
        }
        
    }
}

Views/Shared/ProductSummary.cshtml
@model Product
@{
    <div class="card card-outline-primary m-1 p-1">
            <div class="bg-faded p-1">
                <h4>
                @Model?.Name
                    <span class="badge rounded-pill bg-primary text-white"
                        style="float:right">
                        <small>@Model?.Price.ToString("C")</small>
                    </span>
                </h4>
            </div>
            <form id="@Model?.ProductId" asp-page="/Cart" method="post">
                <input type="hidden" asp-for="ProductId"/>
                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
                    <span class="card-text p-1">
                        @Model?.Description
                        <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">Add To Cart</button>
                    </span>
            </form>
            
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportsStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportsStore.styles.css" asp-append-version="true" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">
                    SportsStore
                </div>
                <div class="col-6 navbar-text text-end">
                    <vc:cart-summary/>
                </div>
            </div>
        </div>
    </div>
        
    <div class="row m-1 P-1">
        <div id="categories" class="col-3">
            <vc:navigation-menu/>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SportsStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>