Models/Cart.cs
namespace SportsStore.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new();
        public virtual void AddItem(Product product,int quantity)
        {
            CartLine? line = Lines.Where(p => p.Product.ProductId == product.ProductId).FirstOrDefault();
            if(line == null)
            {
                Lines.Add(new CartLine { Product = product,Qunatity = quantity});
            }
            else
            {
                line.Qunatity += quantity; 
            }
        }
        public virtual void RemoveLine(Product product) =>
            Lines.RemoveAll(line => line.Product.ProductId == product.ProductId);

        public decimal ComputeTotalValue() =>
            Lines.Sum(line => line.Product.Price * line.Qunatity);

        public virtual void Clear() => Lines.Clear();
    }
    public class CartLine
    {
        public int CartLineId { get; set; }
        public Product Product { get; set; } = new();
        public int Qunatity { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
namespace SportsStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repo;
        private Cart cart;
        public OrderController(IOrderRepository repo, Cart cart)
        {
            this.repo = repo;
            this.cart = cart;
        }
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            if(!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry your cart is empty");
            }
            if(ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repo.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed",new { orderId = order.OrderId});
            }
            else
            {
                return View();
            }
        }
        
    }
}

Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SportsStore.Infrastructure;
using SportsStore.Models;

namespace SportsStore.Pages
{
    public class CartModel : PageModel
    {
        public IStoreRepository repo;


        public CartModel(IStoreRepository repo,Cart cartService)
        {
            this.repo = repo;
            this.Cart= cartService;
        }
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; } = "/";

        public void OnGet(string returnUrl)
        {
            ReturnUrl= returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }
        public IActionResult OnPost(long productId , string returnUrl ) 
        {
            Product? product = repo.Products.FirstOrDefault(p => p.ProductId == productId);
            if(product != null)
            {
                //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart ();
                Cart.AddItem(product, 1);
                //HttpContext.Session.SetJson("cart", Cart);
            }
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long productId , string returnUrl)
        {
            
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Product.ProductId == productId).Product);
            return RedirectToPage(new {returnUrl= returnUrl});
        }
    }
}

Pages/Completed.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SportsStore.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Cart.cshtml
@page
@model CartModel
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var line in Model?.Cart.Lines ?? Enumerable.Empty<CartLine>())
        {
            <tr>
                <td class="text-center">@line.Qunatity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("C")</td>
                <td class="text-right">@((line.Product.Price*line.Qunatity).ToString("C"))</td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="ProductID"
                            value="@line.Product.ProductId" />
                        <input type="hidden" name="returnUrl"
                            value="@Model?.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">
                Total :
            </td>
            <td class="text-right">@Model?.Cart?.ComputeTotalValue()</td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="checkout" asp-controller="Order">CheckOut</a>
</div>

Pages/Completed.cshtml
@page
<div class="text-center">
    <h2 class="display-2">Thanks!</h2>
    <p>Thank you for placing order #@OrderId</p>
    <p>We`ll ship your goods as soon as possible.</p>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Return to Store</a>
</div>
@functions{
    [BindProperty(SupportsGet =true)]
    public string? OrderId { get; set; }
}

Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SportsStore.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">SportsStore</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>